import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/component/layout/Header";
import SessionProviderWrapper from "@/component/SessionProviderWrapper";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${roboto.variable} antialiased`}>
        <SessionProviderWrapper>
          <main className="w-full">
            <Header />
            {children}
          </main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}

